#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
07_rf_feature_extraction.py

Random Forest feature extraction by soil depth.

This script must be run AFTER:
    scripts/06_ml_classification.py

Primary feature representation
------------------------------
Counts
    -> per-sample relative abundance
    -> log10(relative abundance + 1e-6)
    -> Random Forest

Purpose
-------
The fitted Random Forest model provides feature-importance values but does
not by itself indicate whether a predictive taxon is associated with the
upper or lower soil profile.

This script therefore:

1. Loads the fitted Random Forest pipeline.
2. Loads the exact feature names used during model fitting.
3. Recovers the exact training samples used by the fitted model.
4. Applies the preprocessing stored in the fitted pipeline.
5. Verifies that stored preprocessing matches LOG10_RA directly.
6. Extracts Random Forest feature importance.
7. Compares mean transformed abundance between Upper and Lower soil.
8. Assigns each feature a depth association.
9. Saves complete and top-ranked feature tables.
10. Generates the Random Forest feature-importance figure.

Repository structure
--------------------
Input:
    data/Allmerged_16Slevel-2.xlsx

Required model files:
    output/ml/log10_ra/
        best_random_forest_log10_ra.joblib
        rf_feature_names_log10_ra.csv
        rf_training_indices_log10_ra.csv

Tabular outputs:
    output/rf_features/
        RF_all_features_by_depth_log10_ra.csv
        RF_top_lower_soil_features_log10_ra.csv
        RF_top_upper_soil_features_log10_ra.csv
        RF_top_features_by_depth_log10_ra.csv

Figure outputs:
    figures/
        RF_top_features_by_depth_log10_ra.png
        RF_top_features_by_depth_log10_ra.pdf
"""


# =============================================================================
# Imports
# =============================================================================

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from matplotlib.patches import Patch


# =============================================================================
# 0) CONFIGURATION
# =============================================================================

NORMALIZATION = "LOG10_RA"


# -----------------------------------------------------------------------------
# Input phylum-level feature table
# -----------------------------------------------------------------------------

EXCEL_PATH = (
    Path("data")
    / "Allmerged_16Slevel-2.xlsx"
)


# -----------------------------------------------------------------------------
# Fitted-model outputs generated by 06_ml_classification.py
# -----------------------------------------------------------------------------

MODEL_DIR = (
    Path("output")
    / "ml"
    / "log10_ra"
)


# -----------------------------------------------------------------------------
# Tabular feature-extraction outputs
# -----------------------------------------------------------------------------

OUTPUT_DIR = (
    Path("output")
    / "rf_features"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# -----------------------------------------------------------------------------
# Final manuscript figures
# -----------------------------------------------------------------------------

FIGURE_DIR = Path("figures")

FIGURE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# -----------------------------------------------------------------------------
# Number of leading features retained per soil-depth direction
# -----------------------------------------------------------------------------

TOP_N_PER_DEPTH = 10


print("=" * 78)

print(
    "RANDOM FOREST FEATURE EXTRACTION BY SOIL DEPTH"
)

print("=" * 78)


print(
    f"Normalization: {NORMALIZATION}"
)


print(
    f"Input table: {EXCEL_PATH}"
)


print(
    f"Model directory: {MODEL_DIR}"
)


print(
    f"Feature output directory: {OUTPUT_DIR}"
)


print(
    f"Figure directory: {FIGURE_DIR}"
)


# =============================================================================
# 1) DEFINE THE EXACT TRANSFORMATION USED WHEN THE MODEL WAS FITTED
# =============================================================================
#
# IMPORTANT:
#
# This function must exist before joblib.load() because the saved sklearn
# FunctionTransformer references this function.
# =============================================================================

def log10_relative_abundance_transform(
    X,
    pseudocount=1e-6
):
    """
    Convert each sample to relative abundance and then apply:

        log10(relative abundance + pseudocount)

    This must exactly match the transformation used in the LOG10_RA
    machine-learning pipeline.
    """

    X = np.asarray(
        X,
        dtype=float
    ).copy()


    # Prevent negative abundance values
    X[
        X < 0
    ] = 0.0


    # Calculate per-sample totals
    row_sums = X.sum(
        axis=1,
        keepdims=True
    )


    # Avoid division by zero
    row_sums[
        row_sums == 0
    ] = 1.0


    # Convert counts to relative abundance
    X_ra = (
        X
        / row_sums
    )


    # Apply LOG10 transformation
    return np.log10(
        X_ra
        + pseudocount
    )


# =============================================================================
# 2) LOCATE FITTED RANDOM FOREST MODEL AND SUPPORTING FILES
# =============================================================================

rf_model_path = (
    MODEL_DIR
    / (
        "best_random_forest_"
        f"{NORMALIZATION.lower()}.joblib"
    )
)


rf_feature_names_path = (
    MODEL_DIR
    / (
        "rf_feature_names_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


rf_train_index_path = (
    MODEL_DIR
    / (
        "rf_training_indices_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


print(
    "\nExpected model files:"
)


print(
    f"  {rf_model_path}"
)


print(
    f"  {rf_feature_names_path}"
)


print(
    f"  {rf_train_index_path}"
)


# =============================================================================
# 3) VERIFY REQUIRED FILES EXIST
# =============================================================================

if not EXCEL_PATH.exists():

    raise FileNotFoundError(
        "\nInput abundance table not found:\n"
        f"{EXCEL_PATH}\n\n"
        "Run this script from the repository root directory."
    )


if not rf_model_path.exists():

    raise FileNotFoundError(
        "\nRandom Forest model file not found:\n"
        f"{rf_model_path}\n\n"
        "Run scripts/06_ml_classification.py with "
        "NORMALIZATION='LOG10_RA' first."
    )


if not rf_feature_names_path.exists():

    raise FileNotFoundError(
        "\nRandom Forest feature-name file not found:\n"
        f"{rf_feature_names_path}"
    )


if not rf_train_index_path.exists():

    raise FileNotFoundError(
        "\nRandom Forest training-index file not found:\n"
        f"{rf_train_index_path}"
    )


# =============================================================================
# 4) LOAD FITTED RANDOM FOREST PIPELINE
# =============================================================================

best_rf_model = joblib.load(
    rf_model_path
)


print(
    "\nSuccessfully loaded fitted Random Forest pipeline."
)


print(
    "\nPipeline steps:"
)


for (
    step_name,
    step_object
) in best_rf_model.steps:

    print(
        f"  {step_name}: "
        f"{type(step_object).__name__}"
    )


# =============================================================================
# 5) LOAD EXACT FEATURE NAMES USED DURING MODEL FITTING
# =============================================================================

feature_names = (
    pd.read_csv(
        rf_feature_names_path
    )["Feature"]
    .astype(str)
    .to_numpy()
)


print(
    f"\nFeatures used by model: "
    f"{len(feature_names)}"
)


# =============================================================================
# 6) LOAD EXACT TRAINING INDICES AND SOIL-DEPTH LABELS
# =============================================================================

training_info = pd.read_csv(
    rf_train_index_path
)


required_training_columns = [
    "row_index",
    "SoilProfile",
]


missing_training_columns = [

    c

    for c in required_training_columns

    if c not in training_info.columns
]


if missing_training_columns:

    raise ValueError(
        "Training-index file is missing required columns: "
        f"{missing_training_columns}"
    )


row_index = (
    training_info[
        "row_index"
    ]
    .astype(int)
    .to_numpy()
)


train_depth = (
    training_info[
        "SoilProfile"
    ]
    .astype(str)
    .str.strip()
    .str.upper()
    .replace(
        {
            "UPPER":
                "U",

            "LOWER":
                "L",
        }
    )
    .to_numpy()
)


print(
    f"\nTraining samples recovered: "
    f"{len(row_index)}"
)


print(
    "Training depth counts:"
)


print(
    pd.Series(
        train_depth
    )
    .value_counts()
    .to_string()
)


# =============================================================================
# 7) RELOAD ORIGINAL ABUNDANCE TABLE EXACTLY AS IN ML SCRIPT
# =============================================================================

df = pd.read_excel(
    EXCEL_PATH,
    index_col=0
)


# -----------------------------------------------------------------------------
# Remove Archaea
# -----------------------------------------------------------------------------

df = df.loc[
    :,
    ~df.columns.str.startswith(
        "d__Archaea;"
    )
]


# -----------------------------------------------------------------------------
# Remove bacterial-domain prefix
# -----------------------------------------------------------------------------

df.columns = (
    df.columns
    .str.replace(
        r"^d__Bacteria;",
        "",
        regex=True
    )
)


# =============================================================================
# 8) DEFINE METADATA AND TAXONOMIC COLUMNS EXACTLY AS IN ML SCRIPT
# =============================================================================

metadata_cols = [

    "#SampleID",

    "index",

    "SampleCode",

    "LinkerPrimerSequence",

    "BarcodeSequence",

    "Time Period",

    "Species",

    "Amendment",

    "SoilProfile",

    "Block",

    "Group1",

    "Group2",

    "Group3",
]


taxa_cols = [

    c

    for c in df.columns

    if c not in metadata_cols
]


df_taxa = (
    df[
        taxa_cols
    ]
    .apply(
        pd.to_numeric,
        errors="coerce"
    )
    .fillna(0)
)


print(
    f"\nOriginal taxonomic features: "
    f"{df_taxa.shape[1]}"
)


# =============================================================================
# 9) APPLY THE SAME PREVALENCE FILTER USED DURING MODEL FITTING
# =============================================================================
#
# Retain taxa with >= 2 reads in >= 2 samples.
# =============================================================================

df_taxa_filtered = (
    df_taxa.loc[
        :,
        (
            df_taxa >= 2
        ).sum(
            axis=0
        ) >= 2
    ]
)


print(
    f"Features after prevalence filtering: "
    f"{df_taxa_filtered.shape[1]}"
)


# =============================================================================
# 10) VERIFY EXACT FEATURE IDENTITY AND ORDER
# =============================================================================

current_feature_names = np.asarray(
    df_taxa_filtered.columns
)


if not np.array_equal(
    current_feature_names,
    feature_names
):

    print(
        "\nERROR: feature names or feature order "
        "do not match the fitted Random Forest model."
    )


    print(
        f"Current features: "
        f"{len(current_feature_names)}"
    )


    print(
        f"Saved features: "
        f"{len(feature_names)}"
    )


    current_set = set(
        current_feature_names
    )


    saved_set = set(
        feature_names
    )


    only_current = (
        current_set
        - saved_set
    )


    only_saved = (
        saved_set
        - current_set
    )


    if only_current:

        print(
            "\nOnly in current table:"
        )

        print(
            sorted(
                only_current
            )
        )


    if only_saved:

        print(
            "\nOnly in fitted-model feature list:"
        )

        print(
            sorted(
                only_saved
            )
        )


    raise RuntimeError(
        "\nFeature names/order do not match "
        "the fitted Random Forest model.\n"
        "Make sure the same input table and prevalence filtering are used."
    )


print(
    "\nFeature names/order match fitted model: YES"
)


# =============================================================================
# 11) RECOVER THE EXACT RANDOM FOREST TRAINING MATRIX
# =============================================================================

X_all = (
    df_taxa_filtered
    .to_numpy(
        dtype=float
    )
)


if np.max(
    row_index
) >= X_all.shape[0]:

    raise IndexError(
        "Training row indices exceed the number "
        "of rows in the current input table."
    )


X_train = X_all[
    row_index
]


print(
    f"\nRecovered training matrix: "
    f"{X_train.shape}"
)


# =============================================================================
# 12) APPLY PREPROCESSING STORED IN THE FITTED RF PIPELINE
# =============================================================================
#
# For the LOG10_RA model, this should perform:
#
#     counts
#       -> relative abundance
#       -> log10(relative abundance + 1e-6)
#
# The transformer is obtained directly from the fitted pipeline so that
# feature extraction uses the exact representation used during model fitting.
# =============================================================================

X_train_transformed = np.asarray(
    X_train,
    dtype=float
).copy()


print(
    "\nApplying preprocessing stored in fitted RF pipeline:"
)


for (
    step_name,
    transformer
) in best_rf_model.steps[:-1]:

    print(
        f"  Applying: {step_name}"
    )

    X_train_transformed = (
        transformer.transform(
            X_train_transformed
        )
    )


X_train_transformed = np.asarray(
    X_train_transformed,
    dtype=float
)


print(
    "Transformed training matrix shape:",
    X_train_transformed.shape
)


print(
    "Transformed value range:",
    (
        float(
            np.nanmin(
                X_train_transformed
            )
        ),

        float(
            np.nanmax(
                X_train_transformed
            )
        ),
    )
)


# =============================================================================
# 13) VERIFY AGAINST DIRECT LOG10_RA TRANSFORMATION
# =============================================================================
#
# This confirms that the preprocessing recovered from the fitted pipeline
# matches:
#
#     log10(relative abundance + 1e-6)
# =============================================================================

direct_transformed = (
    log10_relative_abundance_transform(
        X_train,
        pseudocount=1e-6
    )
)


transform_match = np.allclose(
    X_train_transformed,
    direct_transformed,
    rtol=1e-10,
    atol=1e-12
)


print(
    "\nPipeline preprocessing matches direct "
    f"LOG10_RA calculation: {transform_match}"
)


if not transform_match:

    max_difference = np.max(
        np.abs(
            X_train_transformed
            - direct_transformed
        )
    )


    print(
        f"Maximum discrepancy: "
        f"{max_difference:.12g}"
    )


    raise RuntimeError(
        "Stored Random Forest preprocessing does not match "
        "the expected LOG10_RA transformation."
    )


# =============================================================================
# 14) EXTRACT RANDOM FOREST MODEL AND FEATURE IMPORTANCES
# =============================================================================

if "rf" not in best_rf_model.named_steps:

    raise KeyError(
        "The fitted pipeline does not contain "
        "a step named 'rf'."
    )


rf_model = (
    best_rf_model
    .named_steps[
        "rf"
    ]
)


rf_importance = np.asarray(
    rf_model.feature_importances_,
    dtype=float
)


if len(
    rf_importance
) != len(
    feature_names
):

    raise RuntimeError(
        "Number of Random Forest importance values does not match "
        "the number of taxonomic features."
    )


print(
    f"\nRandom Forest importance values extracted: "
    f"{len(rf_importance)}"
)


print(
    f"Importance sum: "
    f"{rf_importance.sum():.6f}"
)


# =============================================================================
# 15) IDENTIFY UPPER AND LOWER TRAINING SAMPLES
# =============================================================================

upper_mask = (
    train_depth == "U"
)


lower_mask = (
    train_depth == "L"
)


if not np.any(
    upper_mask
):

    raise RuntimeError(
        "No upper-soil ('U') samples were found "
        "in the Random Forest training data."
    )


if not np.any(
    lower_mask
):

    raise RuntimeError(
        "No lower-soil ('L') samples were found "
        "in the Random Forest training data."
    )


print(
    f"\nUpper training samples: "
    f"{upper_mask.sum()}"
)


print(
    f"Lower training samples: "
    f"{lower_mask.sum()}"
)


# =============================================================================
# 16) CALCULATE MEAN TRANSFORMED ABUNDANCE BY DEPTH
# =============================================================================
#
# These means use the same representation supplied to Random Forest:
#
#     log10(relative abundance + 1e-6)
# =============================================================================

upper_mean = np.asarray(
    X_train_transformed[
        upper_mask
    ].mean(
        axis=0
    ),
    dtype=float
)


lower_mean = np.asarray(
    X_train_transformed[
        lower_mask
    ].mean(
        axis=0
    ),
    dtype=float
)


difference = (
    upper_mean
    - lower_mean
)


# =============================================================================
# 17) DETERMINE DEPTH ASSOCIATION
# =============================================================================
#
# Positive Upper - Lower:
#     greater transformed abundance in upper soil.
#
# Negative Upper - Lower:
#     greater transformed abundance in lower soil.
#
# IMPORTANT:
#
# Random Forest feature importance itself does NOT encode direction.
# The Upper/Lower label is assigned separately using mean transformed
# abundance differences between depth groups.
# =============================================================================

depth_association = np.where(
    difference > 0,

    "Upper soil",

    np.where(
        difference < 0,
        "Lower soil",
        "Equal"
    )
)


# =============================================================================
# 18) BUILD COMPLETE RANDOM FOREST FEATURE TABLE
# =============================================================================

rf_features = pd.DataFrame(
    {

        "Feature":
            feature_names,

        "RF_Importance":
            rf_importance,

        "Upper_Mean_Log10_RA":
            upper_mean,

        "Lower_Mean_Log10_RA":
            lower_mean,

        "Upper_minus_Lower_Log10_RA":
            difference,

        "Depth_Association":
            depth_association,
    }
)


rf_features = (
    rf_features
    .sort_values(
        "RF_Importance",
        ascending=False
    )
    .reset_index(
        drop=True
    )
)


rf_features[
    "Overall_RF_Rank"
] = np.arange(
    1,
    len(
        rf_features
    ) + 1
)


# =============================================================================
# 19) EXTRACT TOP LOWER-SOIL-ASSOCIATED FEATURES
# =============================================================================

top_lower = (
    rf_features[
        rf_features[
            "Depth_Association"
        ] == "Lower soil"
    ]
    .head(
        TOP_N_PER_DEPTH
    )
    .copy()
    .reset_index(
        drop=True
    )
)


top_lower[
    "Depth_Rank"
] = np.arange(
    1,
    len(
        top_lower
    ) + 1
)


# =============================================================================
# 20) EXTRACT TOP UPPER-SOIL-ASSOCIATED FEATURES
# =============================================================================

top_upper = (
    rf_features[
        rf_features[
            "Depth_Association"
        ] == "Upper soil"
    ]
    .head(
        TOP_N_PER_DEPTH
    )
    .copy()
    .reset_index(
        drop=True
    )
)


top_upper[
    "Depth_Rank"
] = np.arange(
    1,
    len(
        top_upper
    ) + 1
)


# =============================================================================
# 21) COMBINE TOP FEATURES
# =============================================================================

top_features_by_depth = pd.concat(
    [
        top_lower,
        top_upper
    ],
    ignore_index=True
)


# =============================================================================
# 22) TABULAR OUTPUT PATHS
# =============================================================================

all_features_path = (
    OUTPUT_DIR
    / (
        "RF_all_features_by_depth_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


top_lower_path = (
    OUTPUT_DIR
    / (
        "RF_top_lower_soil_features_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


top_upper_path = (
    OUTPUT_DIR
    / (
        "RF_top_upper_soil_features_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


combined_path = (
    OUTPUT_DIR
    / (
        "RF_top_features_by_depth_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


# =============================================================================
# 23) SAVE CSV OUTPUTS
# =============================================================================

rf_features.to_csv(
    all_features_path,
    index=False
)


top_lower.to_csv(
    top_lower_path,
    index=False
)


top_upper.to_csv(
    top_upper_path,
    index=False
)


top_features_by_depth.to_csv(
    combined_path,
    index=False
)


# =============================================================================
# 24) PRINT TOP LOWER-SOIL-ASSOCIATED FEATURES
# =============================================================================

print(
    "\n"
    + "=" * 78
)


print(
    "TOP LOWER-SOIL-ASSOCIATED RANDOM FOREST FEATURES"
)


print(
    "=" * 78
)


print(
    top_lower[
        [
            "Depth_Rank",
            "Feature",
            "RF_Importance",
            "Lower_Mean_Log10_RA",
            "Upper_Mean_Log10_RA",
        ]
    ]
    .to_string(
        index=False
    )
)


# =============================================================================
# 25) PRINT TOP UPPER-SOIL-ASSOCIATED FEATURES
# =============================================================================

print(
    "\n"
    + "=" * 78
)


print(
    "TOP UPPER-SOIL-ASSOCIATED RANDOM FOREST FEATURES"
)


print(
    "=" * 78
)


print(
    top_upper[
        [
            "Depth_Rank",
            "Feature",
            "RF_Importance",
            "Upper_Mean_Log10_RA",
            "Lower_Mean_Log10_RA",
        ]
    ]
    .to_string(
        index=False
    )
)


# =============================================================================
# 26) PREPARE FEATURE-IMPORTANCE PLOT
# =============================================================================

plot_upper = (
    top_upper
    .sort_values(
        "RF_Importance",
        ascending=True
    )
    .copy()
)


plot_lower = (
    top_lower
    .sort_values(
        "RF_Importance",
        ascending=True
    )
    .copy()
)


plot_df = pd.concat(
    [
        plot_upper,
        plot_lower
    ],
    ignore_index=True
)


plot_colors = (
    plot_df[
        "Depth_Association"
    ]
    .map(
        {

            "Lower soil":
                "#1f77b4",

            "Upper soil":
                "#ff7f0e",
        }
    )
)


# =============================================================================
# 27) CREATE FEATURE-IMPORTANCE FIGURE
# =============================================================================

plt.figure(
    figsize=(
        10,
        8
    )
)


plt.barh(
    plot_df[
        "Feature"
    ],

    plot_df[
        "RF_Importance"
    ],

    color=plot_colors
)


plt.xlabel(
    "Feature Importance",
    fontweight="bold"
)


plt.ylabel(
    ""
)


plt.title(
    "Top Predictive 16S Phyla for Soil Depth",
    fontweight="bold"
)


# =============================================================================
# 28) LEGEND
# =============================================================================

legend_elements = [

    Patch(
        facecolor="#1f77b4",
        label="Lower soil"
    ),

    Patch(
        facecolor="#ff7f0e",
        label="Upper soil"
    )
]


plt.legend(
    handles=legend_elements,
    title="Depth Association",
    loc="lower right"
)


plt.grid(
    axis="x",
    alpha=0.25
)


plt.tight_layout()


# =============================================================================
# 29) SAVE FIGURE TO figures/
# =============================================================================

plot_png_path = (
    FIGURE_DIR
    / (
        "RF_top_features_by_depth_"
        f"{NORMALIZATION.lower()}.png"
    )
)


plot_pdf_path = (
    FIGURE_DIR
    / (
        "RF_top_features_by_depth_"
        f"{NORMALIZATION.lower()}.pdf"
    )
)


plt.savefig(
    plot_png_path,
    dpi=300,
    bbox_inches="tight"
)


plt.savefig(
    plot_pdf_path,
    bbox_inches="tight"
)


plt.show()


# =============================================================================
# 30) FINAL SUMMARY
# =============================================================================

print(
    "\n"
    + "=" * 78
)


print(
    "RANDOM FOREST FEATURE EXTRACTION COMPLETE"
)


print(
    "=" * 78
)


print(
    "\nTransformation:"
)


print(
    "  counts"
)


print(
    "  -> relative abundance"
)


print(
    "  -> log10(relative abundance + 1e-6)"
)


print(
    "\nModel files loaded from:"
)


print(
    f"  {MODEL_DIR}"
)


print(
    "\nTabular feature outputs saved to:"
)


print(
    f"  {OUTPUT_DIR}"
)


print(
    "\nFigure outputs saved to:"
)


print(
    f"  {FIGURE_DIR}"
)


print(
    "\nSaved table files:"
)


print(
    f"  1. {all_features_path.name}"
)


print(
    f"  2. {top_lower_path.name}"
)


print(
    f"  3. {top_upper_path.name}"
)


print(
    f"  4. {combined_path.name}"
)


print(
    "\nSaved figure files:"
)


print(
    f"  5. {plot_png_path.name}"
)


print(
    f"  6. {plot_pdf_path.name}"
)


print(
    "\nTransformation verification:"
)


print(
    f"  Stored pipeline = direct LOG10_RA: "
    f"{transform_match}"
)


print(
    "=" * 78
)
