#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Random Forest feature extraction by soil depth.

This script must be run AFTER the primary LOG10_RA machine-learning
classification script.

Primary feature representation
------------------------------
Counts
    -> per-sample relative abundance
    -> log10(relative abundance + 1e-6)
    -> Random Forest

Purpose
-------
The fitted Random Forest model provides feature-importance values but does
not by itself indicate whether a predictive taxon is associated with the
upper or lower soil profile.

This script therefore:

1. Loads the fitted Random Forest pipeline.
2. Loads the exact feature names used during model fitting.
3. Recovers the exact training samples used by the fitted model.
4. Applies the preprocessing stored in the fitted pipeline.
5. Extracts Random Forest feature importance.
6. Compares mean transformed abundance between Upper and Lower soil.
7. Assigns each feature a depth association.
8. Saves complete and top-ranked feature tables.
9. Generates the feature-importance figure.

Required files
--------------
Generated by the primary ML classification script:

    output/log10_ra/
        best_random_forest_log10_ra.joblib
        rf_feature_names_log10_ra.csv
        rf_training_indices_log10_ra.csv

Input abundance table
---------------------
    Allmerged_16Slevel-2.xlsx

Outputs
-------
Saved to:

    output/rf_features/
"""


# =============================================================================
# Imports
# =============================================================================

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from matplotlib.patches import Patch


# =============================================================================
# 0) Configuration
# =============================================================================

NORMALIZATION = "LOG10_RA"

EXCEL_PATH = "Allmerged_16Slevel-2.xlsx"


# -----------------------------------------------------------------------------
# Directory containing fitted-model outputs from the primary ML script
# -----------------------------------------------------------------------------

MODEL_DIR = (
    Path("output")
    / "log10_ra"
)


# -----------------------------------------------------------------------------
# Directory for feature-extraction outputs
# -----------------------------------------------------------------------------

OUTPUT_DIR = (
    Path("output")
    / "rf_features"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


TOP_N_PER_DEPTH = 10


print("=" * 78)
print("RANDOM FOREST FEATURE EXTRACTION BY SOIL DEPTH")
print("=" * 78)

print(
    f"Normalization: {NORMALIZATION}"
)

print(
    f"Input table: {EXCEL_PATH}"
)

print(
    f"Model directory: {MODEL_DIR}"
)

print(
    f"Feature output directory: {OUTPUT_DIR}"
)


# =============================================================================
# 1) Define the exact transformation used when the model was fitted
# =============================================================================
#
# IMPORTANT:
#
# The function must exist before joblib.load() because the saved sklearn
# FunctionTransformer references this function.
# =============================================================================

def log10_relative_abundance_transform(
    X,
    pseudocount=1e-6
):
    """
    Convert each sample to relative abundance and apply:

        log10(relative abundance + pseudocount)

    This must exactly match the transformation used in the LOG10_RA
    machine-learning pipeline.
    """

    X = np.asarray(
        X,
        dtype=float
    ).copy()

    # Prevent negative abundance values.
    X[
        X < 0
    ] = 0.0

    # Sample totals.
    row_sums = X.sum(
        axis=1,
        keepdims=True
    )

    # Avoid division by zero.
    row_sums[
        row_sums == 0
    ] = 1.0

    # Relative abundance.
    X_ra = (
        X
        / row_sums
    )

    # Log10 transformation after pseudocount addition.
    return np.log10(
        X_ra
        + pseudocount
    )


# =============================================================================
# 2) Locate fitted Random Forest model and supporting files
# =============================================================================

rf_model_path = (
    MODEL_DIR
    / (
        "best_random_forest_"
        f"{NORMALIZATION.lower()}.joblib"
    )
)


rf_feature_names_path = (
    MODEL_DIR
    / (
        "rf_feature_names_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


rf_train_index_path = (
    MODEL_DIR
    / (
        "rf_training_indices_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


print(
    "\nExpected model files:"
)

print(
    f"  {rf_model_path}"
)

print(
    f"  {rf_feature_names_path}"
)

print(
    f"  {rf_train_index_path}"
)


# =============================================================================
# 3) Verify required files exist
# =============================================================================

if not rf_model_path.exists():

    raise FileNotFoundError(
        "\nRandom Forest model file not found:\n"
        f"{rf_model_path}\n\n"
        "Run the primary LOG10_RA ML classification script first."
    )


if not rf_feature_names_path.exists():

    raise FileNotFoundError(
        "\nRandom Forest feature-name file not found:\n"
        f"{rf_feature_names_path}"
    )


if not rf_train_index_path.exists():

    raise FileNotFoundError(
        "\nRandom Forest training-index file not found:\n"
        f"{rf_train_index_path}"
    )


# =============================================================================
# 4) Load fitted Random Forest pipeline
# =============================================================================

best_rf_model = joblib.load(
    rf_model_path
)


print(
    "\nSuccessfully loaded fitted Random Forest pipeline."
)


print(
    "\nPipeline steps:"
)


for (
    step_name,
    step_object
) in best_rf_model.steps:

    print(
        f"  {step_name}: "
        f"{type(step_object).__name__}"
    )


# =============================================================================
# 5) Load exact feature names used during model fitting
# =============================================================================

feature_names = (
    pd.read_csv(
        rf_feature_names_path
    )["Feature"]
    .astype(str)
    .to_numpy()
)


print(
    f"\nFeatures used by model: "
    f"{len(feature_names)}"
)


# =============================================================================
# 6) Load exact training indices and soil-depth labels
# =============================================================================

training_info = pd.read_csv(
    rf_train_index_path
)


required_training_columns = [
    "row_index",
    "SoilProfile",
]


missing_training_columns = [
    c
    for c in required_training_columns
    if c not in training_info.columns
]


if missing_training_columns:

    raise ValueError(
        "Training-index file is missing required columns: "
        f"{missing_training_columns}"
    )


row_index = (
    training_info[
        "row_index"
    ]
    .astype(int)
    .to_numpy()
)


train_depth = (
    training_info[
        "SoilProfile"
    ]
    .astype(str)
    .str.strip()
    .str.upper()
    .to_numpy()
)


print(
    f"\nTraining samples recovered: "
    f"{len(row_index)}"
)


print(
    "Training depth counts:"
)


print(
    pd.Series(
        train_depth
    )
    .value_counts()
    .to_string()
)


# =============================================================================
# 7) Reload original abundance table exactly as in ML script
# =============================================================================

df = pd.read_excel(
    EXCEL_PATH,
    index_col=0
)


# -----------------------------------------------------------------------------
# Remove Archaea
# -----------------------------------------------------------------------------

df = df.loc[
    :,
    ~df.columns.str.startswith(
        "d__Archaea;"
    )
]


# -----------------------------------------------------------------------------
# Remove bacterial-domain prefix
# -----------------------------------------------------------------------------

df.columns = (
    df.columns
    .str.replace(
        r"^d__Bacteria;",
        "",
        regex=True
    )
)


# =============================================================================
# 8) Define metadata and taxonomic columns exactly as in ML script
# =============================================================================

metadata_cols = [
    "#SampleID",
    "index",
    "SampleCode",
    "LinkerPrimerSequence",
    "BarcodeSequence",
    "Time Period",
    "Species",
    "Amendment",
    "SoilProfile",
    "Block",
    "Group1",
    "Group2",
    "Group3",
]


taxa_cols = [
    c
    for c in df.columns
    if c not in metadata_cols
]


df_taxa = (
    df[
        taxa_cols
    ]
    .apply(
        pd.to_numeric,
        errors="coerce"
    )
    .fillna(0)
)


print(
    f"\nOriginal taxonomic features: "
    f"{df_taxa.shape[1]}"
)


# =============================================================================
# 9) Apply the same prevalence filter used during model fitting
# =============================================================================
#
# Retain taxa with >= 2 reads in >= 2 samples.
# =============================================================================

df_taxa_filtered = (
    df_taxa.loc[
        :,
        (
            df_taxa >= 2
        ).sum(
            axis=0
        ) >= 2
    ]
)


print(
    f"Features after prevalence filtering: "
    f"{df_taxa_filtered.shape[1]}"
)


# =============================================================================
# 10) Verify exact feature identity and order
# =============================================================================

current_feature_names = np.asarray(
    df_taxa_filtered.columns
)


if not np.array_equal(
    current_feature_names,
    feature_names
):

    print(
        "\nERROR: feature names or feature order "
        "do not match the fitted Random Forest model."
    )

    print(
        f"Current features: "
        f"{len(current_feature_names)}"
    )

    print(
        f"Saved features: "
        f"{len(feature_names)}"
    )


    current_set = set(
        current_feature_names
    )

    saved_set = set(
        feature_names
    )


    only_current = (
        current_set
        - saved_set
    )

    only_saved = (
        saved_set
        - current_set
    )


    if only_current:

        print(
            "\nOnly in current table:"
        )

        print(
            sorted(
                only_current
            )
        )


    if only_saved:

        print(
            "\nOnly in fitted-model feature list:"
        )

        print(
            sorted(
                only_saved
            )
        )


    raise RuntimeError(
        "\nFeature names/order do not match "
        "the fitted Random Forest model.\n"
        "Make sure the same input table and prevalence filter are used."
    )


print(
    "\nFeature names/order match fitted model: YES"
)


# =============================================================================
# 11) Recover the exact Random Forest training matrix
# =============================================================================

X_all = (
    df_taxa_filtered
    .to_numpy(
        dtype=float
    )
)


if np.max(
    row_index
) >= X_all.shape[0]:

    raise IndexError(
        "Training row indices exceed the number "
        "of rows in the current input table."
    )


X_train = X_all[
    row_index
]


print(
    f"\nRecovered training matrix: "
    f"{X_train.shape}"
)


# =============================================================================
# 12) Apply preprocessing stored in the fitted RF pipeline
# =============================================================================
#
# For the LOG10_RA model this should perform:
#
#     counts
#       -> relative abundance
#       -> log10(relative abundance + 1e-6)
#
# The transformer is obtained directly from the fitted pipeline to ensure
# that feature extraction uses the exact representation used during fitting.
# =============================================================================

X_train_transformed = np.asarray(
    X_train,
    dtype=float
).copy()


print(
    "\nApplying preprocessing stored in fitted RF pipeline:"
)


for (
    step_name,
    transformer
) in best_rf_model.steps[:-1]:

    print(
        f"  Applying: {step_name}"
    )

    X_train_transformed = (
        transformer.transform(
            X_train_transformed
        )
    )


X_train_transformed = np.asarray(
    X_train_transformed,
    dtype=float
)


print(
    "Transformed training matrix shape:",
    X_train_transformed.shape
)


print(
    "Transformed value range:",
    (
        float(
            np.nanmin(
                X_train_transformed
            )
        ),
        float(
            np.nanmax(
                X_train_transformed
            )
        ),
    )
)


# =============================================================================
# 13) Verify against direct LOG10_RA transformation
# =============================================================================
#
# This confirms that the preprocessing recovered from the fitted pipeline
# matches:
#
#     log10(relative abundance + 1e-6)
# =============================================================================

direct_transformed = (
    log10_relative_abundance_transform(
        X_train,
        pseudocount=1e-6
    )
)


transform_match = np.allclose(
    X_train_transformed,
    direct_transformed,
    rtol=1e-10,
    atol=1e-12
)


print(
    "\nPipeline preprocessing matches direct "
    f"LOG10_RA calculation: {transform_match}"
)


if not transform_match:

    max_difference = np.max(
        np.abs(
            X_train_transformed
            - direct_transformed
        )
    )

    print(
        f"Maximum discrepancy: "
        f"{max_difference:.12g}"
    )

    raise RuntimeError(
        "Stored Random Forest preprocessing does not match "
        "the expected LOG10_RA transformation."
    )


# =============================================================================
# 14) Extract Random Forest model and feature importances
# =============================================================================

if "rf" not in best_rf_model.named_steps:

    raise KeyError(
        "The fitted pipeline does not contain "
        "a step named 'rf'."
    )


rf_model = (
    best_rf_model
    .named_steps[
        "rf"
    ]
)


rf_importance = np.asarray(
    rf_model.feature_importances_,
    dtype=float
)


if len(
    rf_importance
) != len(
    feature_names
):

    raise RuntimeError(
        "Number of Random Forest importance values does not match "
        "the number of taxonomic features."
    )


print(
    f"\nRandom Forest importance values extracted: "
    f"{len(rf_importance)}"
)


print(
    f"Importance sum: "
    f"{rf_importance.sum():.6f}"
)


# =============================================================================
# 15) Identify Upper and Lower training samples
# =============================================================================

upper_mask = (
    train_depth == "U"
)


lower_mask = (
    train_depth == "L"
)


if not np.any(
    upper_mask
):

    raise RuntimeError(
        "No upper-soil ('U') samples were found "
        "in the Random Forest training data."
    )


if not np.any(
    lower_mask
):

    raise RuntimeError(
        "No lower-soil ('L') samples were found "
        "in the Random Forest training data."
    )


print(
    f"\nUpper training samples: "
    f"{upper_mask.sum()}"
)


print(
    f"Lower training samples: "
    f"{lower_mask.sum()}"
)


# =============================================================================
# 16) Calculate mean transformed abundance by depth
# =============================================================================
#
# These means use the same representation supplied to Random Forest:
#
#     log10(relative abundance + 1e-6)
# =============================================================================

upper_mean = np.asarray(
    X_train_transformed[
        upper_mask
    ].mean(
        axis=0
    ),
    dtype=float
)


lower_mean = np.asarray(
    X_train_transformed[
        lower_mask
    ].mean(
        axis=0
    ),
    dtype=float
)


difference = (
    upper_mean
    - lower_mean
)


# =============================================================================
# 17) Determine depth association
# =============================================================================
#
# Positive Upper - Lower:
#     greater transformed abundance in upper soil.
#
# Negative Upper - Lower:
#     greater transformed abundance in lower soil.
#
# IMPORTANT:
#
# Random Forest feature importance itself does not encode direction.
# The depth label is assigned separately from the mean transformed abundance
# difference between Upper and Lower training samples.
# =============================================================================

depth_association = np.where(
    difference > 0,

    "Upper soil",

    np.where(
        difference < 0,
        "Lower soil",
        "Equal"
    )
)


# =============================================================================
# 18) Build complete Random Forest feature table
# =============================================================================

rf_features = pd.DataFrame(
    {
        "Feature":
            feature_names,

        "RF_Importance":
            rf_importance,

        "Upper_Mean_Log10_RA":
            upper_mean,

        "Lower_Mean_Log10_RA":
            lower_mean,

        "Upper_minus_Lower_Log10_RA":
            difference,

        "Depth_Association":
            depth_association,
    }
)


rf_features = (
    rf_features
    .sort_values(
        "RF_Importance",
        ascending=False
    )
    .reset_index(
        drop=True
    )
)


rf_features[
    "Overall_RF_Rank"
] = np.arange(
    1,
    len(
        rf_features
    ) + 1
)


# =============================================================================
# 19) Extract top Lower-soil-associated features
# =============================================================================

top_lower = (
    rf_features[
        rf_features[
            "Depth_Association"
        ] == "Lower soil"
    ]
    .head(
        TOP_N_PER_DEPTH
    )
    .copy()
    .reset_index(
        drop=True
    )
)


top_lower[
    "Depth_Rank"
] = np.arange(
    1,
    len(
        top_lower
    ) + 1
)


# =============================================================================
# 20) Extract top Upper-soil-associated features
# =============================================================================

top_upper = (
    rf_features[
        rf_features[
            "Depth_Association"
        ] == "Upper soil"
    ]
    .head(
        TOP_N_PER_DEPTH
    )
    .copy()
    .reset_index(
        drop=True
    )
)


top_upper[
    "Depth_Rank"
] = np.arange(
    1,
    len(
        top_upper
    ) + 1
)


# =============================================================================
# 21) Combine top features
# =============================================================================

top_features_by_depth = pd.concat(
    [
        top_lower,
        top_upper
    ],
    ignore_index=True
)


# =============================================================================
# 22) Output paths
# =============================================================================

all_features_path = (
    OUTPUT_DIR
    / (
        "RF_all_features_by_depth_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


top_lower_path = (
    OUTPUT_DIR
    / (
        "RF_top_lower_soil_features_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


top_upper_path = (
    OUTPUT_DIR
    / (
        "RF_top_upper_soil_features_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


combined_path = (
    OUTPUT_DIR
    / (
        "RF_top_features_by_depth_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


# =============================================================================
# 23) Save CSV outputs
# =============================================================================

rf_features.to_csv(
    all_features_path,
    index=False
)


top_lower.to_csv(
    top_lower_path,
    index=False
)


top_upper.to_csv(
    top_upper_path,
    index=False
)


top_features_by_depth.to_csv(
    combined_path,
    index=False
)


# =============================================================================
# 24) Print top Lower-soil-associated features
# =============================================================================

print(
    "\n"
    + "=" * 78
)


print(
    "TOP LOWER-SOIL-ASSOCIATED RANDOM FOREST FEATURES"
)


print(
    "=" * 78
)


print(
    top_lower[
        [
            "Depth_Rank",
            "Feature",
            "RF_Importance",
            "Lower_Mean_Log10_RA",
            "Upper_Mean_Log10_RA",
        ]
    ]
    .to_string(
        index=False
    )
)


# =============================================================================
# 25) Print top Upper-soil-associated features
# =============================================================================

print(
    "\n"
    + "=" * 78
)


print(
    "TOP UPPER-SOIL-ASSOCIATED RANDOM FOREST FEATURES"
)


print(
    "=" * 78
)


print(
    top_upper[
        [
            "Depth_Rank",
            "Feature",
            "RF_Importance",
            "Upper_Mean_Log10_RA",
            "Lower_Mean_Log10_RA",
        ]
    ]
    .to_string(
        index=False
    )
)


# =============================================================================
# 26) Prepare feature-importance plot
# =============================================================================

plot_upper = (
    top_upper
    .sort_values(
        "RF_Importance",
        ascending=True
    )
    .copy()
)


plot_lower = (
    top_lower
    .sort_values(
        "RF_Importance",
        ascending=True
    )
    .copy()
)


plot_df = pd.concat(
    [
        plot_upper,
        plot_lower
    ],
    ignore_index=True
)


plot_colors = (
    plot_df[
        "Depth_Association"
    ]
    .map(
        {
            "Lower soil":
                "#1f77b4",

            "Upper soil":
                "#ff7f0e",
        }
    )
)


# =============================================================================
# 27) Create feature-importance figure
# =============================================================================

plt.figure(
    figsize=(
        10,
        8
    )
)


plt.barh(
    plot_df[
        "Feature"
    ],

    plot_df[
        "RF_Importance"
    ],

    color=plot_colors
)


plt.xlabel(
    "Feature Importance",
    fontweight="bold"
)


plt.ylabel(
    ""
)


plt.title(
    "Top Predictive 16S Phyla for Soil Depth",
    fontweight="bold"
)


# =============================================================================
# 28) Legend
# =============================================================================

legend_elements = [

    Patch(
        facecolor="#1f77b4",
        label="Lower soil"
    ),

    Patch(
        facecolor="#ff7f0e",
        label="Upper soil"
    )
]


plt.legend(
    handles=legend_elements,
    title="Depth Association",
    loc="lower right"
)


plt.grid(
    axis="x",
    alpha=0.25
)


plt.tight_layout()


# =============================================================================
# 29) Save figure
# =============================================================================

plot_png_path = (
    OUTPUT_DIR
    / (
        "RF_top_features_by_depth_"
        f"{NORMALIZATION.lower()}.png"
    )
)


plot_pdf_path = (
    OUTPUT_DIR
    / (
        "RF_top_features_by_depth_"
        f"{NORMALIZATION.lower()}.pdf"
    )
)


plt.savefig(
    plot_png_path,
    dpi=300,
    bbox_inches="tight"
)


plt.savefig(
    plot_pdf_path,
    bbox_inches="tight"
)


plt.show()


# =============================================================================
# 30) Final summary
# =============================================================================

print(
    "\n"
    + "=" * 78
)


print(
    "RANDOM FOREST FEATURE EXTRACTION COMPLETE"
)


print(
    "=" * 78
)


print(
    "\nTransformation:"
)


print(
    "  log10(relative abundance + 1e-6)"
)


print(
    "\nModel files loaded from:"
)


print(
    f"  {MODEL_DIR}"
)


print(
    "\nAll feature-extraction results saved to:"
)


print(
    f"  {OUTPUT_DIR}"
)


print(
    "\nSaved files:"
)


print(
    f"  1. {all_features_path.name}"
)


print(
    f"  2. {top_lower_path.name}"
)


print(
    f"  3. {top_upper_path.name}"
)


print(
    f"  4. {combined_path.name}"
)


print(
    f"  5. {plot_png_path.name}"
)


print(
    f"  6. {plot_pdf_path.name}"
)


print(
    "\nTransformation verification:"
)


print(
    f"  Stored pipeline = direct LOG10_RA: "
    f"{transform_match}"
)


print(
    "=" * 78
)
