#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
08_rf_taxa_boxplots.py

Relative-abundance boxplots for Random-Forest-prioritized bacterial phyla.

This script must be run AFTER:
    scripts/06_ml_classification.py
    scripts/07_rf_feature_extraction.py

Purpose
-------
The Random Forest feature-extraction analysis identifies taxa that contribute
most strongly to soil-depth classification and assigns each taxon an Upper-
or Lower-soil association based on transformed abundance differences.

This script:

1. Loads the RF-prioritized taxa from Script 07.
2. Reloads the original phylum-level 16S abundance table.
3. Applies the same taxon prevalence filter used in the ML workflow.
4. Calculates relative abundance across all samples.
5. Compares Upper vs Lower soil abundance for each RF-prioritized taxon
   using two-sided Mann-Whitney U tests.
6. Optionally applies Benjamini-Hochberg FDR correction.
7. Generates partitioned relative-abundance boxplots.
8. Saves statistics and publication-quality PNG/PDF figures.

Important distinction
---------------------
Random Forest importance measures predictive contribution and does not itself
provide a statistical test of differential abundance.

The Mann-Whitney U tests performed here are descriptive follow-up comparisons
of the RF-prioritized taxa and are separate from the treatment-adjusted
ANCOM-BC differential-abundance analysis.

Repository structure
--------------------
Input:
    data/Allmerged_16Slevel-2.xlsx

RF feature input:
    output/rf_features/
        RF_top_features_by_depth_log10_ra.csv

Statistical output:
    output/boxplots/
        RF_extracted_taxa_upper_lower_boxplot_statistics_log10_ra.csv

Figure output:
    figures/
        RF_extracted_taxa_boxplots_upper_lower_log10_ra.png
        RF_extracted_taxa_boxplots_upper_lower_log10_ra.pdf
"""


# =============================================================================
# Imports
# =============================================================================

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import mannwhitneyu


# =============================================================================
# 0) CONFIGURATION
# =============================================================================

NORMALIZATION = "LOG10_RA"


# -----------------------------------------------------------------------------
# Input phylum-level abundance table
# -----------------------------------------------------------------------------

EXCEL_PATH = (
    Path("data")
    / "Allmerged_16Slevel-2.xlsx"
)


# -----------------------------------------------------------------------------
# RF features generated by 07_rf_feature_extraction.py
# -----------------------------------------------------------------------------

RF_FEATURE_FILE = (
    Path("output")
    / "rf_features"
    / (
        "RF_top_features_by_depth_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


# -----------------------------------------------------------------------------
# Statistical/tabular outputs
# -----------------------------------------------------------------------------

OUTPUT_DIR = (
    Path("output")
    / "boxplots"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# -----------------------------------------------------------------------------
# Final manuscript figures
# -----------------------------------------------------------------------------

FIGURE_DIR = Path("figures")

FIGURE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# -----------------------------------------------------------------------------
# Statistical settings
# -----------------------------------------------------------------------------

STRICT_CUTOFF = 1e-3

USE_FDR = False

FILTER_ONLY_SIGNIFICANT = False


# -----------------------------------------------------------------------------
# Small positive value used only for plotting zeros on a logarithmic axis
#
# IMPORTANT:
# This does NOT change the values used for the Mann-Whitney U tests.
# -----------------------------------------------------------------------------

PLOT_EPS = 1e-4


# -----------------------------------------------------------------------------
# Figure settings
# -----------------------------------------------------------------------------

TITLE_SIZE = 18

AXIS_LABEL_SIZE = 16

XTICK_SIZE = 14

YTICK_SIZE = 13

LEGEND_SIZE = 12

LEGEND_TITLE_SIZE = 13

STAR_SIZE = 14


# -----------------------------------------------------------------------------
# Soil-depth colors
# -----------------------------------------------------------------------------

COLORS = {

    "U":
        "#ff7f0e",

    "L":
        "#1f77b4",
}


print("=" * 78)

print(
    "RF-PRIORITIZED TAXA: UPPER vs LOWER SOIL BOXPLOTS"
)

print("=" * 78)


print(
    f"Input table: {EXCEL_PATH}"
)


print(
    f"RF feature file: {RF_FEATURE_FILE}"
)


print(
    f"Statistics directory: {OUTPUT_DIR}"
)


print(
    f"Figure directory: {FIGURE_DIR}"
)


# =============================================================================
# 1) VERIFY REQUIRED INPUT FILES
# =============================================================================

if not EXCEL_PATH.exists():

    raise FileNotFoundError(
        "\nInput abundance table not found:\n"
        f"{EXCEL_PATH}\n\n"
        "Run this script from the repository root directory."
    )


if not RF_FEATURE_FILE.exists():

    raise FileNotFoundError(
        "\nRF feature file not found:\n"
        f"{RF_FEATURE_FILE}\n\n"
        "Run scripts/07_rf_feature_extraction.py first."
    )


# =============================================================================
# 2) LOAD RF TAXA EXTRACTED BY SCRIPT 07
# =============================================================================

rf_taxa = pd.read_csv(
    RF_FEATURE_FILE
)


required_columns = [

    "Feature",

    "RF_Importance",

    "Depth_Association",
]


missing_columns = [

    c

    for c in required_columns

    if c not in rf_taxa.columns
]


if missing_columns:

    raise ValueError(
        "RF feature file is missing required columns: "
        f"{missing_columns}"
    )


# Remove duplicate features if any
rf_taxa = (
    rf_taxa
    .drop_duplicates(
        subset="Feature"
    )
    .copy()
)


# =============================================================================
# 3) DEFINE UPPER- AND LOWER-ASSOCIATED RF TAXA
# =============================================================================

upper_table = (
    rf_taxa[
        rf_taxa[
            "Depth_Association"
        ] == "Upper soil"
    ]
    .sort_values(
        "RF_Importance",
        ascending=False
    )
    .copy()
)


lower_table = (
    rf_taxa[
        rf_taxa[
            "Depth_Association"
        ] == "Lower soil"
    ]
    .sort_values(
        "RF_Importance",
        ascending=False
    )
    .copy()
)


upper_feats = (
    upper_table[
        "Feature"
    ]
    .astype(str)
    .tolist()
)


lower_feats = (
    lower_table[
        "Feature"
    ]
    .astype(str)
    .tolist()
)


# Upper-associated taxa appear on left;
# Lower-associated taxa appear on right.
ordered_feats = (
    upper_feats
    + lower_feats
)


if len(
    ordered_feats
) == 0:

    raise RuntimeError(
        "No RF-prioritized taxa were found in the feature file."
    )


print(
    "\nRF taxa loaded:"
)


print(
    f"  Upper-associated: "
    f"{len(upper_feats)}"
)


print(
    f"  Lower-associated: "
    f"{len(lower_feats)}"
)


print(
    f"  Total: "
    f"{len(ordered_feats)}"
)


# =============================================================================
# 4) LOAD ORIGINAL 16S PHYLUM TABLE
# =============================================================================

df = pd.read_excel(
    EXCEL_PATH,
    index_col=0
)


print(
    f"\nOriginal table shape: {df.shape}"
)


# =============================================================================
# 5) REMOVE ARCHAEA
# =============================================================================

df = df.loc[
    :,
    ~df.columns.str.startswith(
        "d__Archaea;"
    )
]


# =============================================================================
# 6) REMOVE BACTERIAL DOMAIN PREFIX
# =============================================================================

df.columns = (
    df.columns
    .str.replace(
        r"^d__Bacteria;",
        "",
        regex=True
    )
)


# =============================================================================
# 7) IDENTIFY TAXONOMIC COLUMNS
# =============================================================================

metadata_cols = [

    "#SampleID",

    "index",

    "SampleCode",

    "LinkerPrimerSequence",

    "BarcodeSequence",

    "Time Period",

    "Species",

    "Amendment",

    "SoilProfile",

    "Block",

    "Group1",

    "Group2",

    "Group3",
]


taxa_cols = [

    c

    for c in df.columns

    if c not in metadata_cols
]


df_taxa = (
    df[
        taxa_cols
    ]
    .apply(
        pd.to_numeric,
        errors="coerce"
    )
    .fillna(0)
)


print(
    f"Taxonomic features before filtering: "
    f"{df_taxa.shape[1]}"
)


# =============================================================================
# 8) APPLY SAME PREVALENCE FILTER AS ML WORKFLOW
#
# Retain taxa with >=2 reads in >=2 samples.
# =============================================================================

df_taxa_filtered = (
    df_taxa.loc[
        :,
        (
            df_taxa >= 2
        ).sum(
            axis=0
        ) >= 2
    ]
)


print(
    f"Taxonomic features after filtering: "
    f"{df_taxa_filtered.shape[1]}"
)


# =============================================================================
# 9) VERIFY ALL RF-PRIORITIZED TAXA ARE PRESENT
# =============================================================================

missing_taxa = [

    feature

    for feature in ordered_feats

    if feature not in df_taxa_filtered.columns
]


if missing_taxa:

    raise ValueError(
        "The following RF-prioritized taxa are not present "
        "in the filtered taxonomic table:\n"
        + "\n".join(
            missing_taxa
        )
    )


print(
    "\nAll RF-prioritized taxa found in abundance table: YES"
)


# =============================================================================
# 10) CALCULATE RELATIVE ABUNDANCE ACROSS ALL SAMPLES
# =============================================================================

X_all = (
    df_taxa_filtered
    .to_numpy(
        dtype=float
    )
)


# Prevent negative values
X_all[
    X_all < 0
] = 0.0


row_sums = X_all.sum(
    axis=1,
    keepdims=True
)


row_sums[
    row_sums == 0
] = 1.0


relative_abundance = (
    X_all
    / row_sums
)


df_rel = pd.DataFrame(

    relative_abundance,

    columns=(
        df_taxa_filtered.columns
    ),

    index=(
        df_taxa_filtered.index
    )
)


# =============================================================================
# 11) CLEAN SOIL-PROFILE LABELS
# =============================================================================

soil_profile = (
    df[
        "SoilProfile"
    ]
    .astype(str)
    .str.strip()
    .str.upper()
    .replace(
        {

            "UPPER":
                "U",

            "LOWER":
                "L",
        }
    )
    .to_numpy()
)


valid_labels = set(
    np.unique(
        soil_profile
    )
)


if not {
    "U",
    "L"
}.issubset(
    valid_labels
):

    raise ValueError(
        "Expected both U and L in SoilProfile. "
        f"Observed labels: {sorted(valid_labels)}"
    )


print(
    "\nSoil-depth sample counts:"
)


print(
    pd.Series(
        soil_profile
    )
    .value_counts()
    .to_string()
)


# =============================================================================
# 12) BUILD LONG-FORM DATAFRAME
# =============================================================================

all_rel = (
    df_rel[
        ordered_feats
    ]
    .copy()
)


all_rel[
    "SoilProfile"
] = soil_profile


all_rel[
    "SampleID"
] = (
    all_rel
    .index
    .astype(str)
)


plot_long = (
    all_rel[
        [
            "SampleID",
            "SoilProfile",
        ]
        + ordered_feats
    ]
    .melt(

        id_vars=[
            "SampleID",
            "SoilProfile",
        ],

        var_name="Feature",

        value_name="Relative_Abundance"
    )
)


# =============================================================================
# 13) MANN-WHITNEY U TESTS
#
# IMPORTANT:
# Tests use the actual relative-abundance values, including zeros.
# No pseudocount is introduced into the statistical test.
# =============================================================================

stat_rows = []


for feature in ordered_feats:


    upper_values = (
        plot_long.loc[
            (
                plot_long[
                    "Feature"
                ] == feature
            )
            &
            (
                plot_long[
                    "SoilProfile"
                ] == "U"
            ),
            "Relative_Abundance",
        ]
        .to_numpy(
            dtype=float
        )
    )


    lower_values = (
        plot_long.loc[
            (
                plot_long[
                    "Feature"
                ] == feature
            )
            &
            (
                plot_long[
                    "SoilProfile"
                ] == "L"
            ),
            "Relative_Abundance",
        ]
        .to_numpy(
            dtype=float
        )
    )


    if (
        upper_values.size == 0
        or
        lower_values.size == 0
    ):

        statistic = np.nan

        p_value = np.nan


    else:

        try:

            statistic, p_value = (
                mannwhitneyu(

                    upper_values,

                    lower_values,

                    alternative="two-sided",

                    method="auto"
                )
            )


        except TypeError:

            statistic, p_value = (
                mannwhitneyu(

                    upper_values,

                    lower_values,

                    alternative="two-sided"
                )
            )


    feature_row = (
        rf_taxa.loc[
            rf_taxa[
                "Feature"
            ] == feature
        ]
        .iloc[0]
    )


    stat_rows.append(
        {

            "Feature":
                feature,

            "RF_Depth_Association":
                feature_row[
                    "Depth_Association"
                ],

            "RF_Importance":
                float(
                    feature_row[
                        "RF_Importance"
                    ]
                ),

            "Upper_n":
                int(
                    upper_values.size
                ),

            "Lower_n":
                int(
                    lower_values.size
                ),

            "Upper_Median_RelAbund":
                float(
                    np.median(
                        upper_values
                    )
                )
                if upper_values.size
                else np.nan,

            "Lower_Median_RelAbund":
                float(
                    np.median(
                        lower_values
                    )
                )
                if lower_values.size
                else np.nan,

            "MannWhitney_U":
                statistic,

            "p_value":
                p_value,
        }
    )


stats_table = pd.DataFrame(
    stat_rows
)


# =============================================================================
# 14) OPTIONAL BENJAMINI-HOCHBERG FDR CORRECTION
# =============================================================================

metric_label = "p"


if USE_FDR:

    try:

        from statsmodels.stats.multitest import (
            multipletests
        )


        valid_p = (
            stats_table[
                "p_value"
            ]
            .notna()
        )


        q_values = np.full(
            len(
                stats_table
            ),
            np.nan
        )


        if valid_p.any():

            _, corrected, _, _ = (
                multipletests(

                    stats_table.loc[
                        valid_p,
                        "p_value"
                    ].to_numpy(),

                    method="fdr_bh"
                )
            )


            q_values[
                valid_p.to_numpy()
            ] = corrected


        stats_table[
            "q_value"
        ] = q_values


        stats_table[
            "metric"
        ] = q_values


        metric_label = "q"


    except ImportError:

        print(
            "\nstatsmodels is not installed; "
            "raw p-values will be used."
        )


        stats_table[
            "metric"
        ] = (
            stats_table[
                "p_value"
            ]
        )


        metric_label = "p"


else:

    stats_table[
        "metric"
    ] = (
        stats_table[
            "p_value"
        ]
    )


# =============================================================================
# 15) ASSIGN DISPLAY SIGNIFICANCE
#
# *** is displayed only when p/q < 0.001.
# =============================================================================

stats_table[
    "Significance"
] = np.where(

    stats_table[
        "metric"
    ] < STRICT_CUTOFF,

    "***",

    "ns"
)


# =============================================================================
# 16) OPTIONAL SIGNIFICANCE FILTER
# =============================================================================

if FILTER_ONLY_SIGNIFICANT:


    keep_features = (
        stats_table.loc[
            stats_table[
                "metric"
            ] < STRICT_CUTOFF,
            "Feature"
        ]
        .tolist()
    )


    upper_feats = [

        f

        for f in upper_feats

        if f in keep_features
    ]


    lower_feats = [

        f

        for f in lower_feats

        if f in keep_features
    ]


    ordered_feats = (
        upper_feats
        + lower_feats
    )


    if len(
        ordered_feats
    ) == 0:

        raise RuntimeError(
            "No taxa satisfy the requested significance cutoff."
        )


    plot_long = (
        plot_long[
            plot_long[
                "Feature"
            ].isin(
                ordered_feats
            )
        ]
        .copy()
    )


# =============================================================================
# 17) SET FINAL TAXON ORDER
# =============================================================================

plot_long = (
    plot_long[
        plot_long[
            "Feature"
        ].isin(
            ordered_feats
        )
    ]
    .copy()
)


plot_long[
    "Feature"
] = pd.Categorical(

    plot_long[
        "Feature"
    ],

    categories=ordered_feats,

    ordered=True
)


# =============================================================================
# 18) CREATE PLOTTING VALUES
#
# The original relative-abundance values remain unchanged in
# Relative_Abundance.
#
# PLOT_EPS is used only so zeros can be displayed on a logarithmic y-axis.
# =============================================================================

plot_long[
    "Plot_Abundance"
] = np.clip(

    plot_long[
        "Relative_Abundance"
    ].to_numpy(
        dtype=float
    ),

    PLOT_EPS,

    None
)


# =============================================================================
# 19) SAVE STATISTICS TABLE
# =============================================================================

stats_output_path = (
    OUTPUT_DIR
    / (
        "RF_extracted_taxa_"
        "upper_lower_boxplot_statistics_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


stats_table.to_csv(
    stats_output_path,
    index=False
)


# =============================================================================
# 20) CREATE BOXPLOT FIGURE
#
# Use matplotlib directly so the GitHub script has minimal plotting
# dependencies and explicit control over the paired depth boxes.
# =============================================================================

figure_width = max(
    16,
    0.8
    * len(
        ordered_feats
    )
)


fig, ax = plt.subplots(
    figsize=(
        figure_width,
        7
    )
)


# =============================================================================
# 21) PREPARE BOX POSITIONS
# =============================================================================

n_features = len(
    ordered_feats
)


centers = np.arange(
    n_features,
    dtype=float
)


offset = 0.18

box_width = 0.30


upper_positions = (
    centers
    - offset
)


lower_positions = (
    centers
    + offset
)


upper_plot_values = []

lower_plot_values = []


for feature in ordered_feats:


    upper_values = (
        plot_long.loc[
            (
                plot_long[
                    "Feature"
                ] == feature
            )
            &
            (
                plot_long[
                    "SoilProfile"
                ] == "U"
            ),
            "Plot_Abundance",
        ]
        .to_numpy(
            dtype=float
        )
    )


    lower_values = (
        plot_long.loc[
            (
                plot_long[
                    "Feature"
                ] == feature
            )
            &
            (
                plot_long[
                    "SoilProfile"
                ] == "L"
            ),
            "Plot_Abundance",
        ]
        .to_numpy(
            dtype=float
        )
    )


    upper_plot_values.append(
        upper_values
    )


    lower_plot_values.append(
        lower_values
    )


# =============================================================================
# 22) DRAW UPPER-SOIL BOXES
# =============================================================================

upper_boxes = ax.boxplot(

    upper_plot_values,

    positions=upper_positions,

    widths=box_width,

    patch_artist=True,

    showfliers=False,

    manage_ticks=False
)


for patch in upper_boxes[
    "boxes"
]:

    patch.set_facecolor(
        COLORS[
            "U"
        ]
    )


    patch.set_edgecolor(
        "black"
    )


for key in [
    "whiskers",
    "caps",
    "medians",
]:

    for artist in upper_boxes[
        key
    ]:

        artist.set_color(
            "black"
        )


# =============================================================================
# 23) DRAW LOWER-SOIL BOXES
# =============================================================================

lower_boxes = ax.boxplot(

    lower_plot_values,

    positions=lower_positions,

    widths=box_width,

    patch_artist=True,

    showfliers=False,

    manage_ticks=False
)


for patch in lower_boxes[
    "boxes"
]:

    patch.set_facecolor(
        COLORS[
            "L"
        ]
    )


    patch.set_edgecolor(
        "black"
    )


for key in [
    "whiskers",
    "caps",
    "medians",
]:

    for artist in lower_boxes[
        key
    ]:

        artist.set_color(
            "black"
        )


# =============================================================================
# 24) LOGARITHMIC Y-AXIS
# =============================================================================

ax.set_yscale(
    "log"
)


ax.grid(
    axis="y",
    alpha=0.25
)


# =============================================================================
# 25) BACKGROUND PARTITIONS
#
# Left:
#     RF Upper-associated taxa
#
# Right:
#     RF Lower-associated taxa
# =============================================================================

alpha_bg = 0.055


if len(
    upper_feats
) > 0:

    ax.axvspan(

        -0.5,

        len(
            upper_feats
        ) - 0.5,

        color=COLORS[
            "U"
        ],

        alpha=alpha_bg,

        zorder=0
    )


if len(
    lower_feats
) > 0:

    ax.axvspan(

        len(
            upper_feats
        ) - 0.5,

        len(
            ordered_feats
        ) - 0.5,

        color=COLORS[
            "L"
        ],

        alpha=alpha_bg,

        zorder=0
    )


# =============================================================================
# 26) DIVIDER BETWEEN RF UPPER- AND LOWER-ASSOCIATED TAXA
# =============================================================================

if (
    len(
        upper_feats
    ) > 0
    and
    len(
        lower_feats
    ) > 0
):

    divider_x = (
        len(
            upper_feats
        )
        - 0.5
    )


    ax.axvline(

        divider_x,

        color="black",

        linestyle="--",

        linewidth=1.5,

        zorder=1
    )


# =============================================================================
# 27) ADD SIGNIFICANCE STARS
# =============================================================================

sig_map = dict(
    zip(

        stats_table[
            "Feature"
        ],

        stats_table[
            "Significance"
        ]
    )
)


current_ymin, current_ymax = (
    ax.get_ylim()
)


ax.set_ylim(
    current_ymin,
    current_ymax
    * 1.45
)


_, ymax = (
    ax.get_ylim()
)


for i, feature in enumerate(
    ordered_feats
):


    if sig_map.get(
        feature,
        "ns"
    ) != "***":

        continue


    feature_values = (
        plot_long.loc[
            plot_long[
                "Feature"
            ] == feature,
            "Plot_Abundance"
        ]
        .to_numpy(
            dtype=float
        )
    )


    if feature_values.size == 0:

        continue


    y95 = np.percentile(
        feature_values,
        95
    )


    y_star = min(

        y95
        * 1.25,

        ymax
        * 0.88
    )


    ax.text(

        i,

        y_star,

        "***",

        ha="center",

        va="bottom",

        fontsize=STAR_SIZE,

        fontweight="bold"
    )


# =============================================================================
# 28) AXIS LABELS
# =============================================================================

ax.set_xlabel(
    "Bacterial Groups",
    fontsize=AXIS_LABEL_SIZE,
    fontweight="bold"
)


ax.set_ylabel(
    "Relative Abundance (log scale)",
    fontsize=AXIS_LABEL_SIZE,
    fontweight="bold"
)


ax.set_title(
    (
        "Random Forest-Prioritized Phyla by Soil Depth\n"
        f"({metric_label} < {STRICT_CUTOFF:g} shown as ***)"
    ),
    fontsize=TITLE_SIZE,
    pad=25
)


# =============================================================================
# 29) TAXON LABELS
# =============================================================================

ax.set_xticks(
    centers
)


ax.set_xticklabels(
    ordered_feats,
    rotation=45,
    ha="right",
    rotation_mode="anchor",
    fontsize=XTICK_SIZE
)


ax.tick_params(
    axis="y",
    labelsize=YTICK_SIZE
)


# =============================================================================
# 30) CLEAN SPINES
# =============================================================================

ax.spines[
    "top"
].set_visible(
    False
)


ax.spines[
    "right"
].set_visible(
    False
)


# =============================================================================
# 31) LEGEND
# =============================================================================

from matplotlib.patches import Patch


legend_handles = [

    Patch(
        facecolor=COLORS[
            "U"
        ],
        edgecolor="black",
        label="Upper soil"
    ),

    Patch(
        facecolor=COLORS[
            "L"
        ],
        edgecolor="black",
        label="Lower soil"
    ),
]


ax.legend(

    handles=legend_handles,

    title="Soil Depth",

    frameon=False,

    loc="upper right",

    bbox_to_anchor=(
        1.02,
        1.22
    ),

    fontsize=LEGEND_SIZE,

    title_fontsize=LEGEND_TITLE_SIZE
)


# =============================================================================
# 32) FINAL LAYOUT
# =============================================================================

plt.tight_layout()


plt.subplots_adjust(
    bottom=0.30
)


# =============================================================================
# 33) SAVE FIGURES TO figures/
# =============================================================================

png_output_path = (
    FIGURE_DIR
    / (
        "RF_extracted_taxa_"
        "boxplots_upper_lower_"
        f"{NORMALIZATION.lower()}.png"
    )
)


pdf_output_path = (
    FIGURE_DIR
    / (
        "RF_extracted_taxa_"
        "boxplots_upper_lower_"
        f"{NORMALIZATION.lower()}.pdf"
    )
)


plt.savefig(

    png_output_path,

    dpi=300,

    bbox_inches="tight"
)


plt.savefig(

    pdf_output_path,

    bbox_inches="tight"
)


plt.close(
    fig
)


# =============================================================================
# 34) FINAL SUMMARY
# =============================================================================

print(
    "\n"
    + "=" * 78
)


print(
    "RF TAXA BOXPLOT ANALYSIS COMPLETE"
)


print(
    "=" * 78
)


print(
    "\nStatistics saved to:"
)


print(
    f"  {stats_output_path}"
)


print(
    "\nFigures saved to:"
)


print(
    f"  {png_output_path}"
)


print(
    f"  {pdf_output_path}"
)


print(
    "\nUpper-associated RF taxa plotted on LEFT:"
)


for feature in upper_feats:

    print(
        f"  {feature}"
    )


print(
    "\nLower-associated RF taxa plotted on RIGHT:"
)


for feature in lower_feats:

    print(
        f"  {feature}"
    )


print(
    "\nStatistical comparison:"
)


print(
    "  Two-sided Mann-Whitney U test"
)


print(
    "  Tests performed on untransformed relative abundance"
)


if USE_FDR:

    print(
        "  Benjamini-Hochberg FDR correction: ON"
    )

else:

    print(
        "  Benjamini-Hochberg FDR correction: OFF"
    )


print(
    "\nPlotting:"
)


print(
    f"  Zeros displayed as {PLOT_EPS:g} "
    "only for visualization on the log axis"
)


print(
    "=" * 78
)
