# =============================================================================
# 03) BOXPLOTS FOR EXTRACTED RANDOM-FOREST TAXA
# Upper-soil-associated taxa on the LEFT
# Lower-soil-associated taxa on the RIGHT
#
# This script is designed to run AFTER:
#   01_soil_depth_modeling_full.py
#   02_RF_feature_extraction_grouped.py
#
# It uses the taxa already extracted in Code 2:
#   RF_top_features_by_depth_log.csv
#
# It then:
#   1. Reloads the original 16S table
#   2. Calculates relative abundance across ALL samples
#   3. Uses the exact upper/lower RF taxa selected in Code 2
#   4. Performs Mann-Whitney U tests for U vs L for each taxon
#   5. Optionally applies FDR correction
#   6. Creates partitioned boxplots
#   7. Saves statistics and publication-quality PNG/PDF figures
# =============================================================================
# =============================================================================
# 04) BOXPLOTS FOR RANDOM-FOREST-PRIORITIZED TAXA
#
# Upper-soil-associated taxa on the LEFT
# Lower-soil-associated taxa on the RIGHT
#
# This script is designed to run AFTER:
#   01_groupaware_depth_classification.py
#   03_rf_feature_extraction_by_depth.py
#
# It uses the taxa prioritized by Random Forest and extracted in the
# preceding feature-extraction analysis:
#
#   output/rf_features/RF_top_features_by_depth_log10_ra.csv
#
# The script:
#   1. Reloads the original 16S abundance table
#   2. Calculates relative abundance across all samples
#   3. Uses the Upper/Lower-associated RF taxa selected previously
#   4. Performs Mann-Whitney U tests comparing Upper vs Lower soil
#   5. Optionally applies FDR correction
#   6. Creates partitioned boxplots
#   7. Saves statistics and publication-quality PNG/PDF figures
#
# Outputs are written to:
#   output/boxplots/
# =============================================================================


# =============================================================================
# Imports
# =============================================================================

from pathlib import Path

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.stats import mannwhitneyu


# =============================================================================
# 0) SETTINGS
# =============================================================================

NORMALIZATION = "LOG"   # must match Code 1 and Code 2

EXCEL_PATH = "data/Allmerged_16Slevel-2.xlsx"

OUTPUT_DIR = Path("output")

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# File generated by Code 2
RF_FEATURE_FILE = (
    OUTPUT_DIR
    / f"RF_top_features_by_depth_{NORMALIZATION.lower()}.csv"
)

# Statistical settings
STRICT_CUTOFF = 1e-3
USE_FDR = False

# If True, only taxa meeting the significance threshold are plotted
FILTER_ONLY_SIGNIFICANT = False

# Avoid log(0)
EPS = 1e-4


# =============================================================================
# Font sizes
# =============================================================================

TITLE_SIZE = 18
AXIS_LABEL_SIZE = 16
XTICK_SIZE = 14
YTICK_SIZE = 13
LEGEND_SIZE = 12
LEGEND_TITLE_SIZE = 13
STAR_SIZE = 14


# =============================================================================
# Colors
# =============================================================================

COLORS = {
    "U": "#ff7f0e",    # Upper soil = orange
    "L": "#1f77b4",    # Lower soil = blue
}


# =============================================================================
# 1) LOAD RF TAXA EXTRACTED IN CODE 2
# =============================================================================

if not RF_FEATURE_FILE.exists():

    raise FileNotFoundError(
        f"Could not find:\n{RF_FEATURE_FILE}\n\n"
        "Run Code 2 first."
    )


rf_taxa = pd.read_csv(
    RF_FEATURE_FILE
)


required_columns = [
    "Feature",
    "RF_Importance",
    "Depth_Association",
]


missing_columns = [
    c
    for c in required_columns
    if c not in rf_taxa.columns
]


if missing_columns:

    raise ValueError(
        "The RF feature file is missing required columns: "
        f"{missing_columns}"
    )


# Remove duplicate features if any
rf_taxa = (
    rf_taxa
    .drop_duplicates(
        subset="Feature"
    )
    .copy()
)


# =============================================================================
# 2) DEFINE UPPER AND LOWER TAXA USING CODE-2 ASSOCIATION
# =============================================================================

upper_table = (
    rf_taxa[
        rf_taxa[
            "Depth_Association"
        ] == "Upper soil"
    ]
    .sort_values(
        "RF_Importance",
        ascending=False
    )
    .copy()
)


lower_table = (
    rf_taxa[
        rf_taxa[
            "Depth_Association"
        ] == "Lower soil"
    ]
    .sort_values(
        "RF_Importance",
        ascending=False
    )
    .copy()
)


upper_feats = (
    upper_table[
        "Feature"
    ]
    .astype(str)
    .tolist()
)


lower_feats = (
    lower_table[
        "Feature"
    ]
    .astype(str)
    .tolist()
)


# Upper taxa first = left side of plot
# Lower taxa second = right side of plot
ordered_feats = (
    upper_feats
    + lower_feats
)


boundary_idx = (
    len(
        upper_feats
    )
    - 1
)


print(
    "=" * 78
)

print(
    "RF TAXA LOADED FROM CODE 2"
)

print(
    "=" * 78
)

print(
    f"Upper-soil-associated taxa: "
    f"{len(upper_feats)}"
)

print(
    f"Lower-soil-associated taxa: "
    f"{len(lower_feats)}"
)

print(
    f"Total taxa for boxplots: "
    f"{len(ordered_feats)}"
)


# =============================================================================
# 3) LOAD ORIGINAL 16S DATA
# =============================================================================

df = pd.read_excel(
    EXCEL_PATH,
    index_col=0
)


# Drop Archaea exactly as in Code 1
df = df.loc[
    :,
    ~df.columns.str.startswith(
        "d__Archaea;"
    )
]


# Strip Bacteria prefix exactly as in Code 1
df.columns = (
    df.columns
    .str.replace(
        r"^d__Bacteria;",
        "",
        regex=True
    )
)


metadata_cols = [
    "#SampleID",
    "index",
    "SampleCode",
    "LinkerPrimerSequence",
    "BarcodeSequence",
    "Time Period",
    "Species",
    "Amendment",
    "SoilProfile",
    "Block",
    "Group1",
    "Group2",
    "Group3",
]


taxa_cols = [
    c
    for c in df.columns
    if c not in metadata_cols
]


df_taxa = (
    df[
        taxa_cols
    ]
    .apply(
        pd.to_numeric,
        errors="coerce"
    )
    .fillna(0)
)


# Same prevalence filter as Code 1
df_taxa_filtered = (
    df_taxa.loc[
        :,
        (
            df_taxa >= 2
        ).sum(
            axis=0
        ) >= 2
    ]
)


# =============================================================================
# 4) VERIFY ALL EXTRACTED TAXA EXIST
# =============================================================================

missing_taxa = [
    f
    for f in ordered_feats
    if f not in df_taxa_filtered.columns
]


if missing_taxa:

    raise ValueError(
        "The following RF taxa are not present in the filtered "
        "taxonomic table:\n"
        + "\n".join(
            missing_taxa
        )
    )


# =============================================================================
# 5) CALCULATE RELATIVE ABUNDANCE ACROSS ALL SAMPLES
# =============================================================================

X_all = (
    df_taxa_filtered
    .to_numpy(
        dtype=float
    )
)


row_sums = X_all.sum(
    axis=1,
    keepdims=True
)


row_sums[
    row_sums == 0
] = 1.0


df_rel = pd.DataFrame(
    X_all
    / row_sums,

    columns=(
        df_taxa_filtered.columns
    ),

    index=(
        df_taxa_filtered.index
    )
)


# =============================================================================
# 6) CLEAN SOIL-PROFILE LABELS
# =============================================================================

y_text = (
    df[
        "SoilProfile"
    ]
    .astype(str)
    .str.strip()
    .str.upper()
    .replace(
        {
            "UPPER": "U",
            "LOWER": "L",
        }
    )
    .to_numpy()
)


valid_labels = set(
    np.unique(
        y_text
    )
)


if not {
    "U",
    "L"
}.issubset(
    valid_labels
):

    raise ValueError(
        "Expected both U and L in SoilProfile. "
        f"Observed labels: {sorted(valid_labels)}"
    )


# =============================================================================
# 7) BUILD LONG/TIDY DATAFRAME FOR EXTRACTED TAXA
# =============================================================================

all_rel = (
    df_rel[
        ordered_feats
    ]
    .copy()
)


all_rel[
    "SoilProfile"
] = y_text


all_rel[
    "SampleID"
] = (
    all_rel
    .index
    .astype(str)
)


plot_long = (
    all_rel[
        [
            "SampleID",
            "SoilProfile",
        ]
        + ordered_feats
    ]
    .melt(
        id_vars=[
            "SampleID",
            "SoilProfile",
        ],

        var_name="Feature",

        value_name="Abundance"
    )
)


# Avoid zero values on log scale
plot_long[
    "Abundance"
] = np.clip(
    plot_long[
        "Abundance"
    ].to_numpy(
        dtype=float
    ),
    EPS,
    None
)


# =============================================================================
# 8) MANN-WHITNEY U TESTS
# =============================================================================

stat_rows = []


for feature in ordered_feats:

    upper_values = (
        plot_long.loc[
            (
                plot_long[
                    "Feature"
                ] == feature
            )
            & (
                plot_long[
                    "SoilProfile"
                ] == "U"
            ),
            "Abundance",
        ]
        .to_numpy(
            dtype=float
        )
    )


    lower_values = (
        plot_long.loc[
            (
                plot_long[
                    "Feature"
                ] == feature
            )
            & (
                plot_long[
                    "SoilProfile"
                ] == "L"
            ),
            "Abundance",
        ]
        .to_numpy(
            dtype=float
        )
    )


    if (
        upper_values.size == 0
        or lower_values.size == 0
    ):

        statistic = np.nan
        p_value = 1.0

    else:

        try:

            statistic, p_value = (
                mannwhitneyu(
                    upper_values,
                    lower_values,
                    alternative="two-sided",
                    method="auto"
                )
            )

        except TypeError:

            statistic, p_value = (
                mannwhitneyu(
                    upper_values,
                    lower_values,
                    alternative="two-sided"
                )
            )


    stat_rows.append(
        {
            "Feature":
                feature,

            "RF_Depth_Association":
                (
                    "Upper soil"
                    if feature in upper_feats
                    else "Lower soil"
                ),

            "RF_Importance":
                float(
                    rf_taxa.loc[
                        rf_taxa[
                            "Feature"
                        ] == feature,
                        "RF_Importance"
                    ].iloc[0]
                ),

            "Upper_n":
                int(
                    upper_values.size
                ),

            "Lower_n":
                int(
                    lower_values.size
                ),

            "Upper_Median_RelAbund":
                float(
                    np.median(
                        upper_values
                    )
                ),

            "Lower_Median_RelAbund":
                float(
                    np.median(
                        lower_values
                    )
                ),

            "MannWhitney_U":
                statistic,

            "p_value":
                p_value,
        }
    )


stats_table = pd.DataFrame(
    stat_rows
)


# =============================================================================
# 9) OPTIONAL FDR CORRECTION
# =============================================================================

metric_label = "p"


if USE_FDR:

    try:

        from statsmodels.stats.multitest import multipletests


        _, q_values, _, _ = (
            multipletests(
                stats_table[
                    "p_value"
                ].to_numpy(),
                method="fdr_bh"
            )
        )


        stats_table[
            "metric"
        ] = q_values


        stats_table[
            "q_value"
        ] = q_values


        metric_label = "q"


    except ImportError:

        print(
            "\nstatsmodels is not installed. "
            "Using raw p-values instead."
        )


        stats_table[
            "metric"
        ] = (
            stats_table[
                "p_value"
            ]
        )


        metric_label = "p"


else:

    stats_table[
        "metric"
    ] = (
        stats_table[
            "p_value"
        ]
    )


# =============================================================================
# 10) ASSIGN SIGNIFICANCE LABELS
# =============================================================================
#
# This preserves your original strict display:
# *** only when p/q < STRICT_CUTOFF
#
# Everything else receives no star on the figure.
# =============================================================================

stats_table[
    "Significance"
] = np.where(
    stats_table[
        "metric"
    ] < STRICT_CUTOFF,
    "***",
    "ns"
)


# =============================================================================
# 11) OPTIONAL SIGNIFICANCE FILTER
# =============================================================================

if FILTER_ONLY_SIGNIFICANT:

    keep_features = (
        stats_table.loc[
            stats_table[
                "metric"
            ] < STRICT_CUTOFF,
            "Feature"
        ]
        .tolist()
    )


    upper_feats = [
        f
        for f in upper_feats
        if f in keep_features
    ]


    lower_feats = [
        f
        for f in lower_feats
        if f in keep_features
    ]


    ordered_feats = (
        upper_feats
        + lower_feats
    )


    boundary_idx = (
        len(
            upper_feats
        )
        - 1
    )


    plot_long = (
        plot_long[
            plot_long[
                "Feature"
            ].isin(
                ordered_feats
            )
        ]
        .copy()
    )


# =============================================================================
# 12) SET FINAL PLOTTING ORDER
# =============================================================================

plot_long = (
    plot_long[
        plot_long[
            "Feature"
        ].isin(
            ordered_feats
        )
    ]
    .copy()
)


plot_long[
    "Feature"
] = pd.Categorical(
    plot_long[
        "Feature"
    ],

    categories=ordered_feats,

    ordered=True
)


# =============================================================================
# 13) SAVE STATISTICS TABLE
# =============================================================================

stats_output_path = (
    OUTPUT_DIR
    / (
        "RF_extracted_taxa_"
        "upper_lower_boxplot_statistics_"
        f"{NORMALIZATION.lower()}.csv"
    )
)


stats_table.to_csv(
    stats_output_path,
    index=False
)


# =============================================================================
# 14) CREATE BOXPLOT FIGURE
# =============================================================================

sns.set_style(
    "whitegrid"
)


# Wider figure when many taxa are present
figure_width = max(
    16,
    0.8
    * len(
        ordered_feats
    )
)


fig, ax = plt.subplots(
    figsize=(
        figure_width,
        7
    )
)


box = sns.boxplot(
    data=plot_long,

    x="Feature",

    y="Abundance",

    hue="SoilProfile",

    hue_order=[
        "U",
        "L",
    ],

    palette=COLORS,

    showfliers=False,

    width=0.72,

    ax=ax
)


# =============================================================================
# 15) LOG SCALE
# =============================================================================

ax.set_yscale(
    "log"
)


# Give extra space at top for stars
current_ymin, current_ymax = (
    ax.get_ylim()
)


ax.set_ylim(
    current_ymin,
    current_ymax
    * 1.35
)


ymin, ymax = (
    ax.get_ylim()
)


# =============================================================================
# 16) BACKGROUND PARTITIONS
# =============================================================================

alpha_bg = 0.055


# Upper-associated taxa: left side
if len(
    upper_feats
) > 0:

    ax.axvspan(
        -0.5,
        len(
            upper_feats
        )
        - 0.5,

        color=COLORS[
            "U"
        ],

        alpha=alpha_bg,

        zorder=0
    )


# Lower-associated taxa: right side
if len(
    lower_feats
) > 0:

    ax.axvspan(
        len(
            upper_feats
        )
        - 0.5,

        len(
            ordered_feats
        )
        - 0.5,

        color=COLORS[
            "L"
        ],

        alpha=alpha_bg,

        zorder=0
    )


# =============================================================================
# 17) VERTICAL DIVIDER BETWEEN RF DEPTH GROUPS
# =============================================================================

if (
    len(
        upper_feats
    ) > 0
    and len(
        lower_feats
    ) > 0
):

    divider_x = (
        len(
            upper_feats
        )
        - 0.5
    )


    ax.axvline(
        divider_x,

        color="black",

        linestyle="--",

        linewidth=2,

        zorder=1
    )


# =============================================================================
# 18) ADD SIGNIFICANCE STARS
# =============================================================================

sig_map = dict(
    zip(
        stats_table[
            "Feature"
        ],

        stats_table[
            "Significance"
        ]
    )
)


for i, feature in enumerate(
    ordered_feats
):

    if sig_map.get(
        feature,
        "ns"
    ) != "***":

        continue


    feature_values = (
        plot_long.loc[
            plot_long[
                "Feature"
            ] == feature,
            "Abundance"
        ]
        .to_numpy(
            dtype=float
        )
    )


    if feature_values.size == 0:

        continue


    # Place stars slightly above the upper distribution
    y95 = np.percentile(
        feature_values,
        95
    )


    y_star = min(
        y95
        * 1.20,
        ymax
        * 0.88
    )


    ax.text(
        i,

        y_star,

        "***",

        ha="center",

        va="bottom",

        fontsize=STAR_SIZE,

        fontweight="bold"
    )


# =============================================================================
# 19) AXIS LABELS AND TITLE
# =============================================================================

ax.set_xlabel(
    "Bacterial Groups",
    fontsize=AXIS_LABEL_SIZE,
    fontweight="bold"
)


ax.set_ylabel(
    "Relative Abundance (log scale)",
    fontsize=AXIS_LABEL_SIZE,
    fontweight="bold"
)


ax.set_title(
    (
        "Top Predictive Phyla by Soil Depth\n"
        f"({metric_label} < {STRICT_CUTOFF:g})"
    ),

    fontsize=TITLE_SIZE,

    pad=25
)


# =============================================================================
# 20) TICK LABELS
# =============================================================================

plt.setp(
    ax.get_xticklabels(),

    rotation=45,

    ha="right",

    rotation_mode="anchor",

    fontsize=XTICK_SIZE
)


ax.tick_params(
    axis="y",
    labelsize=YTICK_SIZE
)


# =============================================================================
# 21) CLEAN SPINES
# =============================================================================

ax.spines[
    "top"
].set_visible(
    False
)


ax.spines[
    "right"
].set_visible(
    False
)


# =============================================================================
# 22) LEGEND
# =============================================================================

handles, labels = (
    ax.get_legend_handles_labels()
)


label_map = {
    "U":
        "Upper soil",

    "L":
        "Lower soil",
}


display_labels = [
    label_map.get(
        label,
        label
    )
    for label in labels
]


ax.legend(
    handles,

    display_labels,

    title="Depth Association",

    frameon=False,

    loc="upper right",

    bbox_to_anchor=(
        1.02,
        1.22
    ),

    fontsize=LEGEND_SIZE,

    title_fontsize=LEGEND_TITLE_SIZE
)


# =============================================================================
# 23) SAVE FIGURE
# =============================================================================

plt.tight_layout()


plt.subplots_adjust(
    bottom=0.30
)


png_output_path = (
    OUTPUT_DIR
    / (
        "RF_extracted_taxa_"
        "boxplots_upper_lower_"
        f"{NORMALIZATION.lower()}.png"
    )
)


pdf_output_path = (
    OUTPUT_DIR
    / (
        "RF_extracted_taxa_"
        "boxplots_upper_lower_"
        f"{NORMALIZATION.lower()}.pdf"
    )
)


plt.savefig(
    png_output_path,

    dpi=300,

    bbox_inches="tight"
)


plt.savefig(
    pdf_output_path,

    bbox_inches="tight"
)


plt.show()


# =============================================================================
# 24) PRINT FINAL SUMMARY
# =============================================================================

print(
    "\n"
    + "=" * 78
)


print(
    "RF TAXA BOXPLOT ANALYSIS COMPLETE"
)


print(
    "=" * 78
)


print(
    f"\nStatistics saved to:\n"
    f"{stats_output_path}"
)


print(
    f"\nPNG figure saved to:\n"
    f"{png_output_path}"
)


print(
    f"\nPDF figure saved to:\n"
    f"{pdf_output_path}"
)


print(
    "\nUpper-associated taxa plotted on LEFT:"
)


for feature in upper_feats:

    print(
        f"  {feature}"
    )


print(
    "\nLower-associated taxa plotted on RIGHT:"
)


for feature in lower_feats:

    print(
        f"  {feature}"
    )


print(
    "\nDone."
)
